apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
  name: {{ include "helmchartbachelor.fullname" . }}
  labels:
    {{- include "helmchartbachelor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmchartbachelor.selectorLabels" . | nindent 4 }}
